Add vulnerability assessment with trivy
20tab/django-continuous-delivery pull request #250
Opened 2023-01-10 09:51 UTC by trottomv

2023-01-10 13:49 UTC, niccolomineo submitted a review, later dismissed

2023-01-10 17:36 UTC, pauloxnet requested changes
Copy here changes from https://github.com/20tab/django-continuous-delivery/pull/257 (see comments)

2023-01-11 10:01 UTC, trottomv commented
> Copy here changes from #257 (see comments)

ok

2023-01-19 10:06 UTC, pauloxnet requested changes

2023-01-19 10:06 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/.gitlab-ci.yml
> +      --env TRIVY_CACHE_DIR=.trivicache/
```suggestion
      --env TRIVY_CACHE_DIR=.trivycache/
```

2023-01-19 14:20 UTC, trottomv commented on {{cookiecutter.project_dirname}}/.gitlab-ci.yml
> +    - docker cp trivy-{{ cookiecutter.project_slug }}-{{ cookiecutter.service_slug }}-${CI_JOB_ID}:/tmp/${REPORT_NAME}.html trivy/report.html || true
```suggestion
    - docker cp trivy-{{ cookiecutter.project_slug }}-{{ cookiecutter.service_slug }}-${CI_JOB_ID}:/tmp/report.html trivy/report.html || true
```

2023-01-25 08:05 UTC, trottomv commented
consider it a spike for now, postponed

2023-01-25 08:05 UTC, closed without merging