Feature/813 configurations tests
20tab/django-continuous-delivery pull request #251
Opened 2023-01-10 11:06 UTC by trottomv

2023-01-10 13:53 UTC, niccolomineo submitted a review, later dismissed

2023-01-10 17:44 UTC, pauloxnet requested changes

2023-01-10 17:44 UTC, pauloxnet commented on .github/workflows/test.yml
> +    - name: Set up Python 3.10
Upgrade to 3.11

2023-01-10 17:44 UTC, pauloxnet commented on .github/workflows/test.yml
> +        python -m pip install --upgrade pip
Remove this extra step

2023-01-10 17:44 UTC, pauloxnet commented on .github/workflows/test.yml
> +        python -m pip install --upgrade pip
Remove this extra step

2023-01-10 17:44 UTC, pauloxnet commented on .pre-commit-config.yaml
> +    rev: "v4.4.0"
Add this changes in a different PR

2023-01-11 10:14 UTC, trottomv commented on .github/workflows/test.yml
> +    - name: Set up Python 3.10
could be upgraded in a separate PR

2023-01-11 10:14 UTC, trottomv commented on .github/workflows/test.yml
> +        python -m pip install --upgrade pip
ok

2023-01-11 10:15 UTC, trottomv commented on .github/workflows/test.yml
> +        python3 -m isort --check .
could be upgrade in a separate PR

2023-01-11 10:15 UTC, trottomv commented on .github/workflows/test.yml
> +    - name: Set up Python 3.10
could be upgraded in a separate PR

2023-01-11 10:15 UTC, trottomv commented on .github/workflows/test.yml
> +        python -m pip install --upgrade pip
ok

2023-01-11 10:15 UTC, trottomv commented on .github/workflows/test.yml
> +    - name: Set up Python 3.10
could be upgraded in a separate PR

2023-01-11 10:15 UTC, trottomv commented on .github/workflows/test.yml
> +        python -m pip install --upgrade pip
ok

2023-01-11 10:16 UTC, trottomv commented on .pre-commit-config.yaml
> +    rev: "v4.4.0"
ok

2023-01-11 10:31 UTC, pauloxnet commented on .github/workflows/test.yml
> +    - name: Set up Python 3.10
ok

2023-01-25 08:05 UTC, trottomv commented
consider it a spike for now, postponed

2023-01-25 08:05 UTC, closed without merging