clean the code - noqa and pragma
20tab/django-continuous-delivery pull request #256
Opened 2023-01-10 15:13 UTC by Mitchina

2023-01-10 17:17 UTC, pauloxnet requested changes

2023-01-10 17:17 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/{{cookiecutter.django_settings_dirname}}/settings.py
> +            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", # noqa: E501
```suggestion
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa: E501
```
Leave two spaces before comment

2023-01-11 08:19 UTC, Mitchina commented on {{cookiecutter.project_dirname}}/{{cookiecutter.django_settings_dirname}}/settings.py
> +            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator", # noqa: E501
okk

2023-01-11 08:30 UTC, trottomv commented
These changes are too related to upgrade versions and tools of linter checks. 
It should either be expanded or introduced in conjunction with check linter tool and dependency updates

2023-01-11 14:20 UTC, pauloxnet approved these changes

2023-01-11 15:02 UTC, filippo-20tab commented on {{cookiecutter.project_dirname}}/{{cookiecutter.django_settings_dirname}}/settings.py
> +        import sentry_sdk
Sentry is often present but not always. Therefore, I suggest what follows
```suggestion
        import sentry_sdk  # noqa: F401
```

2023-01-11 15:12 UTC, pauloxnet approved these changes

2023-01-11 15:13 UTC, merged