update django configurations
20tab/django-continuous-delivery pull request #258
Opened 2023-01-10 17:21 UTC by Mitchina

2023-01-10 17:34 UTC, pauloxnet requested changes
Copy here changes from #257 (see comments)

2023-01-11 10:01 UTC, pauloxnet approved these changes

2023-01-11 14:20 UTC, pauloxnet approved these changes

2023-01-11 15:18 UTC, filippo-20tab approved these changes

2023-01-11 15:33 UTC, pauloxnet approved these changes

2023-01-11 15:36 UTC, pauloxnet requested changes

2023-01-11 15:36 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/.gitignore
> +.kolo
```suggestion
.kolo
.local
*.bak
```

2023-01-11 15:36 UTC, pauloxnet commented on {{cookiecutter.project_dirname}}/requirements/local.in
> +ipdb~=0.13.0
```suggestion
ipython~=8.8.0
```

2023-01-11 15:43 UTC, merged