TG-1015 Replace `black` with `ruff format`
20tab/django-continuous-delivery pull request #290
Opened 2024-01-03 16:43 UTC by niccolomineo

2024-01-04 18:43 UTC, niccolomineo commented on pyproject.toml
> +    "[{][{]cookiecutter[.]project_dirname[}][}]/.vscode*",
These rules currently make `ruff format` error out. Confirmed to be a [bug](https://github.com/astral-sh/ruff/issues/9381) on their side.

2024-01-05 09:15 UTC, niccolomineo commented
This PR is currently blocked due to the following pyproject rules making `ruff format` error out:

```
extend-exclude = [
    "__pycache__",
    ".vscode*",
]
```

Confirmed to be a [bug](https://github.com/astral-sh/ruff/issues/9381) on their side.

2024-01-11 13:15 UTC, trottomv requested changes

2024-01-11 13:15 UTC, trottomv commented on {{cookiecutter.project_dirname}}/{{cookiecutter.django_settings_dirname}}/settings.py
> +    SESSION_COOKIE_SAMESITE = "Strict"
This seems like a customization for a specific project, it doesn't seem necessary to me include it in the bootstrap.

2024-01-11 13:15 UTC, trottomv commented on {{cookiecutter.project_dirname}}/{{cookiecutter.django_settings_dirname}}/settings.py
> +    CSRF_COOKIE_SAMESITE = "Strict"
As mentioned above, also this seems like a customization for a specific project, it doesn't seem necessary to me include it in the bootstrap.

2024-01-11 14:09 UTC, pauloxnet approved these changes

2024-01-11 14:14 UTC, trottomv approved these changes

2024-01-11 14:16 UTC, merged