TG-1012 Upgrade to Python 3.12
20tab/django-continuous-delivery pull request #293
Opened 2024-01-08 11:58 UTC by niccolomineo

2024-01-08 13:35 UTC, pauloxnet submitted a review, later dismissed

2024-01-10 11:59 UTC, niccolomineo commented on .github/workflows/test.yml
> +        uses: actions/setup-python@v4
```suggestion
        uses: actions/setup-python@v5
```

2024-01-10 11:59 UTC, niccolomineo commented on .github/workflows/test.yml
>        - uses: actions/checkout@v3
```suggestion
      - uses: actions/checkout@v4
```

2024-01-10 12:24 UTC, niccolomineo commented on {{cookiecutter.project_dirname}}/docker-compose.yaml
> +  { { cookiecutter.service_slug } }:
```suggestion
  {{ cookiecutter.service_slug }}:
```

2024-01-10 15:14 UTC, pauloxnet requested changes

2024-01-10 15:14 UTC, pauloxnet commented on .pre-commit-config.yaml
> +    rev: "v4.0.0-alpha.8"
```suggestion
    rev: "v3.1.0"
```

2024-01-10 15:14 UTC, pauloxnet commented on Makefile
> +	python3 -m pip install -q -U pip~=23.3.0 pip-tools~=7.3.0 setuptools~=69.0.0 wheel~=0.42.0
```suggestion
	python3 -m pip install --quiet --upgrade pip~=23.3.0 pip-tools~=7.3.0 setuptools~=69.0.0 wheel~=0.42.0
```

2024-01-10 15:14 UTC, pauloxnet commented on requirements/common.in
>  validators~=0.20.0
```suggestion
validators~=0.22.0
```

2024-01-10 15:19 UTC, niccolomineo commented on requirements/common.in
>  validators~=0.20.0
Purtroppo l'ultima versione spacca i test. Trattiamo l'update a parte.

2024-01-10 15:20 UTC, niccolomineo commented on .pre-commit-config.yaml
> +    rev: "v4.0.0-alpha.8"
Di là siamo andati su con la `v4.0.0-alpha.8`, perché qui la `v3.1.0`? Che problemi hai / avete riscontrato?

2024-01-10 15:44 UTC, pauloxnet approved these changes

2024-01-10 16:28 UTC, merged